version: "3.9"

services:
  api:
    build: ../apps/api
    container_name: ft_api
    ports:
      - "8443:8443"
    volumes:
      - ../apps/api:/app
      - ../infra/certs:/app/infra/certs:ro
      - /app/node_modules    # redémarre si crash
    env_file:
      - ../apps/api/.env
    restart: unless-stopped
    networks:
      - transcendance
  web:
    build: ../apps/web
    container_name: ft_web
    ports:
      - "5173:5173"
    volumes:
      - ../apps/web:/app
      - ../infra/certs:/app/infra/certs:ro
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - transcendance
  prometheus:
    image:  prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom/rules.yml:/etc/prometheus/rules.yml
      - prometheus-storage:/prometheus
    networks:
      - monitoring
    restart: unless-stopped
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node
    ports:
      - "9110:9100"
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports :
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=true
      - GF_SERV_ROOT_URL=http://localhost:3000
      - GF_AUTH_GITHUB_CLIENT_SECRET=${GF_PWD}
      - GF_AUTH_GITHUB_CLIENT_ID=${GF_ID}
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_GITHUB_ENABLED=true
    networks:
      - monitoring
    restart : unless-stopped
  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    volumes:
      - ./prom/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring
  mailhog:
    image: mailhog/mailhog
    networks:
      - monitoring
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  transcendance:
  monitoring:
    driver: bridge

volumes:
  grafana-storage:
  prometheus-storage:

