{
 "title": "Dashboard Transcendance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RAM usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance)((node_filesystem_size_bytes{fstype!=\"tmpfs\"} - node_filesystem_free_bytes{fstype!=\"tmpfs\"}) / node_filesystem_size_bytes{fstype!=\"tmpfs\"} * 100)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Reception)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[30s])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage ",
   "type": "gauge",
   "description": "Usage du CPU,\nnode_cpu  IDLE time -100 pour le temps utilise de chaque instance\navg by prends toutes les instances et fait une moyenne",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[30s]) * 100)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (Transmition)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[30s])\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}